### ISSUE TITLE
params for 128-beam LiDAR

### ISSUE THREAD

**Issue by WSTao** [LimHyungTae/patchwork#5] opened 2021-10-08 08:53 UTC
When I test with 128-beam data, the ground will be under-segmented，how to modify those parameters?
thanks much！

**Comment by LimHyungTae** [comment] 2021-10-08 08:59
Could you please give me some screenshots in rviz? I guess more than 64 channels do not cause the under-segmentation.

**Comment by WSTao** [comment] 2021-10-08 09:52
> Could you please give me some screenshots in rviz? I guess more than 64 channels do not cause the under-segmentation.

![image](https://user-images.githubusercontent.com/30944722/136535611-91123584-802a-430b-a9f8-69df68399f4e.png)
![image](https://user-images.githubusercontent.com/30944722/136536015-e3be010b-5191-44fa-b4ae-f96396eb3ef0.png)
![image](https://user-images.githubusercontent.com/30944722/136536252-eb443e00-c99a-4abe-bbee-fdf2b080f92a.png)

**Comment by LimHyungTae** [comment] 2021-10-08 11:11
Thank you for your fast reply! In addition, could you show the visualized likelihood?? Did you change the parameter `sensor_height` to your own sensor_height?

**Comment by WSTao** [comment] 2021-10-08 11:39
> Thank you for your fast reply! In addition, could you show the visualized likelihood?? Did you change the parameter `sensor_height` to your own sensor_height?
I modified it, but there is no obvious improvement

**Comment by WSTao** [comment] 2021-10-08 11:49
![image](https://user-images.githubusercontent.com/30944722/136551640-54cd9e24-d88a-4a1e-8f49-1d5403e775a2.png)

I modified the parameter flatness_thresholds  and the effect has been significantly improved, but there are still under-segmentation and over-segmentation，how is elevation_thresholds and  flatness_thresholds determined?

**Comment by LimHyungTae** [comment] 2021-10-08 12:00
If then, it denotes that most bins are rejected via elevation filters. I guess your elevation thresholds should be lower than [-1.2, -0.9984, -0.851, -0.605]. As shown in the screenshots, your sensor height is quite high....so how about change the elevation thresholds?
+ you can check the status by visualizing the jsk_rviz_plugin/PolygonArray msg named as `/gpf/plane`

**Comment by WSTao** [comment] 2021-10-08 12:13
> If then, it denotes that most bins are rejected via elevation filters. I guess your elevation thresholds should be lower than [-1.2, -0.9984, -0.851, -0.605]. As shown in the screenshots, your sensor height is quite high....so how about change the elevation thresholds?
> 
> * you can check the status by visualizing the jsk_rviz_plugin/PolygonArray msg named as `/gpf/plane`

My lidar height is 1.98, I will try the method you mentioned，Thank you very much!

**Comment by LimHyungTae** [comment] 2021-10-11 06:03
Hello there, did you solve the problem? Could you share your `/gpf/plane` msg please? I'm curious your situations :)

**Comment by WSTao** [comment] 2021-10-11 07:08
> Hello there, did you solve the problem? Could you share your `/gpf/plane` msg please? I'm curious your situations :)

[likelihood.txt](https://github.com/LimHyungTae/patchwork/files/7320153/likelihood.txt)
Thank you very much, I printed the message, but I don’t know how to analyze it

**Comment by LimHyungTae** [comment] 2021-10-11 07:52
Oh, I mean I'd like to viz GLE as follows:
![image](https://user-images.githubusercontent.com/35317311/136752715-d6610756-a749-4579-bc46-47ee58b2f3fe.png)
You can debug what the problem is via visualized GLE.

**Comment by WSTao** [comment] 2021-10-11 09:26
> Oh, I mean I'd like to viz GLE as follows: ![image](https://user-images.githubusercontent.com/35317311/136752715-d6610756-a749-4579-bc46-47ee58b2f3fe.png) You can debug what the problem is via visualized GLE.
![image](https://user-images.githubusercontent.com/30944722/136766292-c8e29ecd-6078-49d8-aceb-ccba2c8a5907.png)
![image](https://user-images.githubusercontent.com/30944722/136766366-0c0dd4f6-92bd-4275-bda0-45817c2a1a23.png)
![image](https://user-images.githubusercontent.com/30944722/136766564-4a2251c5-c1cf-4a3d-9ddf-a355c281c58f.png)
![image](https://user-images.githubusercontent.com/30944722/136766710-918c0fa8-572b-428e-ab1d-4a535e80aa45.png)

**Comment by LimHyungTae** [comment] 2021-10-12 07:36
Cool! The blue parts denote that your elevation threshold should be fixed. As you mentioned earlier, the height of the platform is 1.98, why don't you change the elevation terms, i.e. [-1.2, -0.9984, -0.851, -0.605], into  [-1.46, -1.256, -1.10, -0.862] or more lower values?

**Comment by WSTao** [comment] 2021-10-13 13:36
Thank you very much, I modified the variable, but the result is basically the same

**Comment by LimHyungTae** [comment] 2021-10-14 07:41
Could you send me some pcds? It would be helpful for generalization of algorithm: shapelim@kaist.ac.kr . I'll check it

**Comment by WSTao** [comment] 2021-10-14 13:23
Thank you for your patience, the pcd file has been sent to you

**Closed as completed** 2021-10-16 04:27 UTC

**Comment by MingXXI** [comment] 2022-11-28 10:59
> Cool! The blue parts denote that your elevation threshold should be fixed. As you mentioned earlier, the height of the platform is 1.98, why don't you change the elevation terms, i.e. [-1.2, -0.9984, -0.851, -0.605], into [-1.46, -1.256, -1.10, -0.862] or more lower values?

Very appreciate your helpful discussion :) Could I get some hint about how the threshold_value are set? According to the comments found in your config, "1.723 - 1.2 = 0.523 is acceptable", I'm wondering how does 1.2 calculated, and is there a proper way to set all thresholds nicely?
